version: "3.8"

services:
  hicdex:
    build: .
    depends_on:
      - db
    volumes:
      - ./src/hicdex:/home/dipdup/source/src/hicdex
      - ./src/hicdex/dipdup.yml:/home/dipdup/dipdup.yml
      - ./src/hicdex/dipdup-docker.yml:/home/dipdup/dipdup-docker.yml
      - ./data/hicdex-metadata:/home/dipdup/metadata
    command: ["-c", "dipdup.yml", "-c", "dipdup-docker.yml", "run"]
    #command: ["schema", "approve"]
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - ADMIN_SECRET=${ADMIN_SECRET:-changeme}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY:-}
      - NOTIFIED_EMAILS=${NOTIFIED_EMAILS:-}

  db:
    image: postgres:13
    shm_size: 6g
    ports:
      - 6423:5432
    restart: always
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dipdup
      - POSTGRES_DB=dipdup
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dipdup"]
      interval: 10s
      timeout: 5s
      retries: 5

  hasura:
    image: hasura/graphql-engine:v2.0.1
    # ports:
    #   - 8081:8080
    expose:
      - 8080
    depends_on:
      - db
    restart: always
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://dipdup:${POSTGRES_PASSWORD:-changeme}@db:5432/dipdup
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup, http-log, webhook-log, websocket-log, query-log
      - HASURA_GRAPHQL_ADMIN_SECRET=${ADMIN_SECRET:-changeme}
      - HASURA_GRAPHQL_UNAUTHORIZED_ROLE=user

  backup:
    container_name: backup
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres # Optional: see below
    volumes:
      - ./data/backups:/backups
    links:
      - db
    depends_on:
      - db
    #ports:
    #  - 8082:8082
    environment:
      - TZ=Europe/Paris
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=dipdup
      - POSTGRES_USER=dipdup
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - POSTGRES_EXTRA_OPTS=-Z6 --clean --schema=public --blobs
      - SCHEDULE=*/30 * * * *
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8082
      
  caddy:
    image: caddy:2.4.0-alpine
    depends_on:
      - "hasura"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../hicdex-graphiql:/srv/api.hicdex.com
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /opt/caddy_data:/data
      - /opt/caddy_config:/config

